define bird_asn = 65000;
define bird_ip4 = 1.2.3.4;
define bird_ip6 = fd00::1234;

define group_main = bird_asn;
define group_geo = bird_asn + 1;

define tag_ip4 = 4;
define tag_ip6 = 6;

define tag_asn = 10;
define tag_geo = tag_asn + 1;

define no_rt4 = [
	0.0.0.0/8+,
	10.0.0.0/8+,
	100.64.0.0/10+,
	127.0.0.0/8+,
	169.254.0.0/16+,
	172.16.0.0/12+,
	192.0.0.0/24+,
	192.168.0.0/16+,
	224.0.0.0/24+,
	240.0.0.0/4+,
	255.255.255.255/32
];

define no_rt6 = [
	::1/128,
	fc00::/7+,
	fe80::/10+,
	ff00::/8+
];

router id bird_ip4;

log "/var/log/bird.log" all;

ipv4 table mixed4;
ipv6 table mixed6;

protocol aggregator a4 {
	# export from:
	table mixed4;
	# import to:
	peer table master4;

	import all;
	export filter {
		if ! (source ~ [RTS_STATIC, RTS_BGP]) then reject;
		if net ~ no_rt4 then reject;
		accept;
	};

	aggregate on net;
	merge by {
		for route r in routes do {
			if ! defined(bgp_path) then { bgp_path = r.bgp_path; }
			bgp_community = bgp_community.add(r.bgp_community);
		}
		accept;
	};
}

protocol aggregator a6 {
	# export from:
	table mixed6;
	# import to:
	peer table master6;

	import all;
	export filter {
		if ! (source ~ [RTS_STATIC, RTS_BGP]) then reject;
		if net ~ no_rt6 then reject;
		accept;
	};

	aggregate on net;
	merge by {
		for route r in routes do {
			if ! defined(bgp_path) then { bgp_path = r.bgp_path; }
			bgp_community = bgp_community.add(r.bgp_community);
		}
		accept;
	};
}

protocol device d0 {
}

protocol kernel k4 {
	ipv4 {
		import none;
		export none;
	};
}

protocol kernel k6 {
	ipv6 {
		import none;
		export none;
	};
}

protocol static s4 {
	description "Generic Static IPv4";
	ipv4 {
		table mixed4;
		import filter {
			bgp_community.add((bird_asn, tag_ip4));
			bgp_community.add((bird_asn, tag_asn));
			bgp_community.add((bird_asn, 100));
			accept;
		};
		export none;
	};
	include "/etc/bird/static.conf.d/*.ipv4.generic.conf";
}

protocol static s6 {
	description "Generic Static IPv6";
	ipv6 {
		table mixed6;
		import filter {
			bgp_community.add((bird_asn, tag_ip6));
			bgp_community.add((bird_asn, tag_asn));
			bgp_community.add((bird_asn, 100));
			accept;
		};
		export none;
	};
	include "/etc/bird/static.conf.d/*.ipv6.generic.conf";
}

include "/etc/bird/static.conf.d/*.proto.*.conf";

template bgp bgp4_tpl {
    local as bird_asn;
    ipv4 { 
        import none;
        export all;
    };
}

template bgp bgp6_tpl {
    local as bird_asn;
    ipv6 { 
        import none;
        export all;
    };
}

protocol bgp bgp4_any from bgp4_tpl {
	dynamic name "bgp_peer";
	passive on;
	multihop;
	neighbor range 0.0.0.0/0 external;
}

protocol bgp bgp6_any from bgp6_tpl {
	dynamic name "bgp_peer";
	passive on;
	multihop;
	neighbor range ::/0 external;
}

include "/etc/bird/bgp.conf.d/*.conf";
