[supervisord]
nodaemon=true
pidfile=/var/run/supervisord.pid
logfile=/var/log/supervisord.log
logfile_maxbytes=128KB

[program:bird]
command=/usr/sbin/bird -c /etc/bird/bird.conf -f -R
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:lgproxy]
command=/usr/local/bin/bird-lgproxy-go --bird /var/run/bird.ctl
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:lg]
command=/usr/local/bin/bird-lg-go --listen=80 --servers="Local<127.0.0.1>" --title-brand="BIRD Looking Glass"
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
