[supervisord]
user=root
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:updater]
command=/bin/sh -c 'until /usr/sbin/birdc -r show status >/dev/null 2>&1; do sleep 1; done; while true; do date +"%%Y-%%m-%%d %%H:%%M:%%S"; if /etc/bird/ipverse.sh && /usr/sbin/birdc configure; then sleep 86400; else sleep 300; fi; done'
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:bird]
command=/usr/sbin/bird -c /etc/bird/bird.conf -f -R
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:proxy]
command=/usr/local/bin/proxy --bird /var/run/bird.ctl --listen 127.0.0.1:8000
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:frontend]
command=/usr/local/bin/frontend --listen=80 --servers="Local<127.0.0.1>" --title-brand="BIRD Looking Glass" --max-response-size=0
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
