# Provider: antifilter.download
# Communities:
# - 65432:100 subnet.lst (https://antifilter.download/list/subnet.lst)
# - 65432:200 ipsum.lst (https://antifilter.download/list/ipsum.lst)
# - 65432:300 ip.lst (https://antifilter.download/list/ip.lst)
# - 65432:400 Google IPv4
# - 65432:500 community.lst (https://community.antifilter.download/list/community.lst)

define group_afd = bird_asn + 2;
define tag_afd = tag_asn + 2;

ipv4 table afd4;
ipv6 table afd6;

protocol bgp bgp_afd {
	local as bird_asn;
	ipv4 {
		table afd4;
		import filter {
			bgp_community.add((bird_asn, tag_ip4));
			bgp_community.add((bird_asn, tag_afd));
			accept;
		};
		export none;
	};
	ipv6 {
		table afd6;
		import filter {
			bgp_community.add((bird_asn, tag_ip6));
			bgp_community.add((bird_asn, tag_afd));
			accept;
		};
		export none;
	};
	multihop;
	neighbor 45.154.73.71 as 65432;
	hold time 240;
}
