# Provider: antifilter.network
# Communities:
# - 65444:100, 65444:110 ipsmart.lst (https://antifilter.network/download/ipsmart.lst)
# - 65444:101-107 Aggregation IPv4 24-32
# - 65444:200, 65444:210 ip.lst (https://antifilter.network/download/ip.lst)
# - 65444:300 ipsum.lst (https://antifilter.network/download/ipsum.lst)
# - 65444:700 Facebook
# - 65444:710 Twitter
# - 65444:720 Netflix
# - 65444:730 Amazon CloudFront
# - 65444:740 Microsoft
# - 65444:750 Amazon
# - 65444:760 OpenAI
# - 65444:770 YouTube
# - 65444:780 Google
# - 65444:790 Telegram
# - 65444:900, 65445:ISO Geo

define group_afn = bird_asn + 3;
define tag_afn = tag_asn + 3;

ipv4 table afn4;
ipv6 table afn6;

protocol bgp bgp_afn {
	local as bird_asn;
	ipv4 {
		table afn4;
		import filter {
			bgp_community.add((bird_asn, tag_ip4));
			bgp_community.add((bird_asn, tag_afn));
			accept;
		};
		export none;
	};
	ipv6 {
		table afn6;
		import filter {
			bgp_community.add((bird_asn, tag_ip6));
			bgp_community.add((bird_asn, tag_afn));
			accept;
		};
		export none;
	};
	multihop;
	neighbor 51.75.66.20 as 65444;
	hold time 240;
}
