# Provider: https://github.com/1andrevich/Re-filter-lists

define group_ref = bird_asn + 4;
define tag_ref = tag_asn + 4;

ipv4 table ref4;
ipv6 table ref6;

protocol bgp bgp_ref {
	local as bird_asn;
	ipv4 {
		table ref4;
		import filter {
			bgp_community.add((bird_asn, tag_ip4));
			bgp_community.add((bird_asn, tag_ref));
			accept;
		};
		export none;
	};
	ipv6 {
		table ref6;
		import filter {
			bgp_community.add((bird_asn, tag_ip6));
			bgp_community.add((bird_asn, tag_ref));
			accept;
		};
		export none;
	};
	multihop;
	neighbor 165.22.127.207 as 65412;
	hold time 240;
}
