# Provider: https://github.com/1andrevich/Re-filter-lists

define asn_ref = 65412;
define ip_ref = 165.22.127.207;
define tag_ref = asn_ref;

ipv4 table ref4;
ipv6 table ref6;

protocol bgp b0_ref {
	description "BGP IPv4+IPv6 REF (Re:filter)";
	local as bird_asn;
	ipv4 {
		table ref4;
		import filter {
			bgp_large_community.add((bird_asn, tag_fam, 4));
			bgp_large_community.add((bird_asn, tag_ref, 0));
			accept;
		};
		export none;
	};
	ipv6 {
		table ref6;
		import filter {
			bgp_large_community.add((bird_asn, tag_fam, 6));
			bgp_large_community.add((bird_asn, tag_ref, 0));
			accept;
		};
		export none;
	};
	multihop;
	neighbor ip_ref as asn_ref;
	hold time 240;
}
